CLEAR_SCREEN_COMMANDS_MAP = {
    'nt' : 'cls',
    'posix' : 'clear',
}
PLAYABLE_SYMBOLS = ['X', 'O']
PLAYGROUND_ROW_LENGTH = 3
WIN_STREAK = 3
BRAINSTORM_MIN_SEC = 2
BRAINSTORM_MAX_SEC = 4
BRAINSTORM_ERROR_SEC = 0.5
AI_WIN_SKIP_CHANCE = 10
AI_DEFENCE_SKIP_CHANCE = 20
AI_OFFENCE_SKIP_CHANCE = 30
AI_LOGGING_FORMAT = '%(asctime)s - [%(levelname)s] - %(message)s'
AI_LOGFILE_FILEPATH = 'ai_moves.log'